workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/mlops-group-40-2026/ml-images/train:latest
    env:
      - name: GCS_MODEL_PATH
        value: gs://mlops-group-40-2026-dvc/models/model.ckpt
